valid_ies=[
'Patient',
'Study',
'Series',
'Equipment',
'Frame of Reference',
'Image',
'Overlay',
'Modality LUT',
'VOI LUT',
'Presentation State',
'Waveform',
'SR Document',
'MR Spectroscopy',
'Raw Data',
'Encapsulated Document',
'Real World Value Mapping',
'Surface',
'Measurements',

'Spatial Fiducials',
'Spatial Registration',
'Treatment Record',
'Dose',
'Structure Set',
'Plan',
'Stereometric Relationship',
'Hanging Protocol',
'Segmentation',
'Color Palette',
'Implant Template',
'Implant Template Group',
'Surface Mesh',
'Implant Assembly',
'Document',
'Deformable Registration',

# IEs corresponding to normalized IODs
'Film Session',
'Basic Film Box',
'Basic Image Box',
'Basic Annotation Box',
'Print Job',
'Printer',
'Storage Commitment',
'Modality Performed Procedure Step',
'Printer Configuration',
'General Purpose Scheduled Procedure Step',
'General Purpose Performed Procedure Step',
'Instance Availability Notification',
'Media Creation Management',
'Unified Procedure Step',
'Rt Conventional Machine Verification',
'Rt Ion Machine Verification',
]

